export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const ADD_PROJECT_FILTER = 'ADD_PROJECT_FILTER';
export const REMOVE_PROJECT_FILTER = 'REMOVE_PROJECT_FILTER';
export const RESET_PROJECT_FILTERS = 'RESET_PROJECT_FILTERS';

export const SET_VIEWPORT = 'SET_VIEWPORT';

export const VIEW_PROJECTS = 'VIEW_PROJECTS';
export const VIEW_ONE_PROJECT = 'VIEW_ONE_PROJECT';

export const FETCH_PROJECTS_DATA = 'FETCH_PROJECTS_DATA';
export const FETCH_PROJECTS_GEOM = 'FETCH_PROJECTS_GEOM';
export const FETCH_USERS_DATA = 'FETCH_USERS_DATA';
